### ISSUE TITLE
Toolbar disappearing

### ISSUE THREAD

**Issue by hclemens** [davcpas1234/MaterialSettings#1]
Hi,

I'm not sure I'm right here, but I came here from your [awesome SO answer](http://stackoverflow.com/a/27455363).
I used the code, you have listed below the Gingerbread-fix, but discovered a problem:
When my nested preference screen (dialog) is opened and I lock my screen, and unlock it some seconds later, the toolbar is gone, and there's only the content of the nested pref.Screen visible.

I hope you encountered this before and know how to fix it.
Thanks in advance!

**Comment by davcpas1234** [comment]
Hi @hclemens ,

Could you provide me a video of the behavior and/or your code implementation so I can investigate?

Thanks

**Comment by davcpas1234** [comment]
I've had a little look using the latest commit 19828449c8bd7d875aa15787b47d5232090fef44 and I cannot reproduce, I am using an emulator running android 2.3.4. See this [Youtube Video](https://www.youtube.com/watch?v=UYNw0GcD8mU)

**Comment by hclemens** [comment]
Thanks a lot for trying and uploading the video. I wanted to share a screencast with you on youtube but can't edit it though (sry).
But I can actually reproduce it again and again, by doing the following:
Open up Settings, open the sub-preference-screen, 
activate lockscreen, wait 10 seconds, and unlocking again
Doing this, the toolbar magically vanishes, until I close the (settings)dialog and open it up again.
[Here is the code](https://github.com/PicFrame/picframe/blob/develop/PicFrame/app/src/main/java/picframe/at/picframe/activities/SettingsActivity.java#L439) it is almost the same to your version I think,

**Comment by davcpas1234** [comment]
Thank you @hclemens I will create a sample project and see what I can find.

**Comment by davcpas1234** [comment]
Found it, it is do with `onConfigurationChanged()` when you are locking your phone, the configuration is changing (I assume this). As, the only way I could reproduce the error was changing the orientation of my emulator. (I know your app is fixed orientation, but my emulator mimics config changes despite this).

add this line to your `SettingsActivity` declaration in your `AndroidManifest.xml`:

``` xml
android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
```

and this to your `SettingsActivity` code:

``` java
@Override
public void onConfigurationChanged(Configuration newConfig) {
    super.onConfigurationChanged(newConfig);
}
```

**Comment by davcpas1234** [comment]
I will leave this open @hclemens until you confirm resolution. I have created a [youtube video](https://www.youtube.com/watch?v=Eh7-DXP7WFs) with your code as demonstration of fixes outlined above.

**Comment by hclemens** [comment]
Ah, awesome! Thanks a lot! I will try it on Saturday or Sunday I hope, and will get back to you right after that.

**Comment by hclemens** [comment]
Thank you a lot, worked instantly! :)

**Comment by davcpas1234** [comment]
Glad to hear it @hclemens
