### ISSUE TITLE
Up affordance not retained after screen rotation

### ISSUE THREAD

**Issue by ChuongPham** [davcpas1234/MaterialSettings#11]
The following method:

`setUpNestedScreen((PreferenceScreen) preference);`

does not recreate the Up affordance button after the screen is physically rotated.

How do I resolve this issue?

**Comment by davcpas1234** [comment]
Will look at this one, may be a result of the savedInstanceState

**Comment by ChuongPham** [comment]
@davcpas1234: Thanks heap.

**Comment by davcpas1234** [comment]
@ChuongPham what version are you using, so that I can create the relevant emulator to test the fix for this?

**Comment by ChuongPham** [comment]
@davcpas1234: Sorry for my late response.

The AVD I used was for Android 5.0 and mobile device running Android 5.0. The Up affordance was removed after a physical rotation of the AVD or the mobile device.

**Comment by davcpas1234** [comment]
I have been unable to duplicate the above @ChuongPham. Double check you have the following line in the activity definition in your `AndroidManifest.xml` file:

`android:configChanges="keyboard|keyboardHidden|orientation|screenSize"`

and this in your `SettingsActivity.java` (or equivalent):

       @Override
        public void onConfigurationChanged(Configuration newConfig) {
            super.onConfigurationChanged(newConfig);
        }

**Comment by ChuongPham** [comment]
@davcpas1234: I can no longer replicate the screen rotation issue with the latest changes that you've made in another bug fix. Thanks for all your help. Much appreciated.

**Comment by davcpas1234** [comment]
No worries @ChuongPham, glad the issues have been fixed 😄
