### ISSUE TITLE
android.os.BadParcelableException

### ISSUE THREAD

**Issue by kosratdev** [davcpas1234/MaterialSettings#14]
Hi, 
my firebase crash reporting reports me this error (**Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v7.widget.Toolbar$SavedState**) on using **MaterialSettings** 
I'm googling it but not found any useful answer.

**Comment by davcpas1234** [comment]
Hi @KosratDAhmad, what line is this being returned and what API level are you using?

**Comment by davcpas1234** [comment]
@KosratDAhmad are you able to test with the new release. Thanks

**Comment by kosratdev** [comment]
@davcpas1234 I have test with latest commit this error will not occur but I used the same code on my project this error will occur 

There is how to test it: 
* Open settings then go to nested preference like notification
* Press home button 
* Terminate the app in Android studio - Android Monitor 
* Open the app again, this error will occur. 

And finally I have resolved it in my project by override **onSaveInstanceState** and **onRestoreInstanceState** with out call super constructor like that:
    
    @Override
    protected void onSaveInstanceState(Bundle outState) {

    }

    @Override
    protected void onRestoreInstanceState(Bundle state) {

    }

**Comment by davcpas1234** [comment]
This is closed with commit 3987ba9
