### ISSUE TITLE
ClassCastException on API level 15

### ISSUE THREAD

**Issue by kosratdev** [davcpas1234/MaterialSettings#15]
Hi, 

My firebase crash reporting reports this error (**java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.ListView**) on api level 15.

**Comment by davcpas1234** [comment]
Hi @KosratDAhmad what line is this reproted against?

**Comment by kosratdev** [comment]
Merge pull request #16 and resolve conflicts
also remove line 50 - 54 to solve issue #18 

look at this image remove code in the boxes will resolve merge conflicts and resolve issue #18 

![selection_004](https://cloud.githubusercontent.com/assets/10336475/22186139/0dd8a058-e102-11e6-917d-e9dfa85f4dc0.png)
