### ISSUE TITLE
Shows Nothing

### ISSUE THREAD

**Issue by kosratdev** [davcpas1234/MaterialSettings#18]
Settings shows nothing in Api Level 25

look at my screen shot:

![device-2017-01-23-001059](https://cloud.githubusercontent.com/assets/10336475/22186044/bc72956c-e100-11e6-9492-3b2bf1a33f20.png)

**Comment by kosratdev** [comment]
It is resolved in pull request #16

**Comment by davcpas1234** [comment]
@KosratDAhmad I have a tentative fix in the works for this, I will update shortly
