### ISSUE TITLE
NPE On Sony Ericsson Running 4.0.4

### ISSUE THREAD

**Issue by fliespl** [davcpas1234/MaterialSettings#2]
LinearLayout root = (LinearLayout) findViewById(android.R.id.list).getParent().getParent().getParent();

Worked when changed to:
`if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN)`

**Comment by davcpas1234** [comment]
I will confirm this on a virtual machine later, seems to be a valid fix. Will confirm.

**Comment by davcpas1234** [comment]
fix confirmed
