### ISSUE TITLE
BindPreferenceSummaryToValue Issue

### ISSUE THREAD

**Issue by IshaanKr** [davcpas1234/MaterialSettings#21]
The function bindPreferenceSummaryToValue is called only once.
For Example,
I have two EditTextPreference which needs to set their summary to corresponding values.
Only the first EditText gets summary updated. Not the second one.
There is no problem in saving and reading the values.
It just the UI which is not nice.

Please fix asap

**Comment by davcpas1234** [comment]
Hi @Ishaan-Kumar,

All you need to do is add an additional line to call the additional `bindPreferenceSummaryToValue()` function. As in the example:

 ```java
bindPreferenceSummaryToValue(findPreference("notifications_ringtone"));
```

so in your case you need to do this:

```java
bindPreferenceSummaryToValue(findPreference("edittext_preference_name1"));
bindPreferenceSummaryToValue(findPreference("edittext_preference_name2"));
```

and you should be good to go. Closing
