### ISSUE TITLE
Android N - Root View Cast Error

### ISSUE THREAD

**Issue by zysidea** [davcpas1234/MaterialSettings#6]
@davcpas1234 
`LinearLayout root = (LinearLayout) findViewById(android.R.id.list).getParent().getParent().getParent();`

this code is error in Android N,  findViewById(android.R.id.list).getParent().getParent().getParent() is FrameLayout.

**Comment by zysidea** [comment]
This code is right :LinearLayout root = (LinearLayout) findViewById(android.R.id.list).getParent().getParent();

**Comment by davcpas1234** [comment]
Thanks for raising this @lollipopidea, I will investigate and correct ASAP.

**Comment by literakl** [comment]
I can confirm this issue as well. Nougat changed layout.

**Comment by davcpas1234** [comment]
Merged pull request from @1priyank1 should resolve this, thanks Priyank
