### ISSUE TITLE
ClassCastException in nested preference screens Android API 24

### ISSUE THREAD

**Issue by salveta** [davcpas1234/MaterialSettings#7]
In Android API 24, in NESTED PREFERENCE SCREENS, in this line ( LinearLayout root = (LinearLayout) dialog.findViewById(android.R.id.list).getParent(); ) I'm getting this error: java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.LinearLayout.

 Is any solution for this???

**Comment by salveta** [comment]
Fixed doing this:

LinearLayout root = (LinearLayout) dialog.findViewById(android.R.id.list).getParent().getParent();

**Comment by davcpas1234** [comment]
Thanks for highlighting this. I will update for N when possible.

**Comment by kosratdev** [comment]
thank you very much

**Comment by davcpas1234** [comment]
Merged pull request from @1priyank1 should resolve this, thanks Priyank
